"""
Django settings for app project.

Generated by 'django-admin startproject' using Django 5.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path
from decouple import config
import dj_database_url
from dotenv import load_dotenv


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# ENV file init
SETTINGS_DIR = BASE_DIR.parent / "settings" / "env"
ENV_PROD = SETTINGS_DIR / '.env.prod'
ENV_DEV = SETTINGS_DIR / '.env.dev'
ENV = SETTINGS_DIR / '.env'
ENV_PROD_EXAMPLE = SETTINGS_DIR / '.env.prod.example'
ENV_DEV_EXAMPLE = SETTINGS_DIR / '.env.dev.example'

if os.path.exists(ENV_PROD):
    load_dotenv(ENV_PROD)
elif os.path.exists(ENV_DEV):
    load_dotenv(ENV_DEV)
elif os.path.exists(ENV):
    load_dotenv(ENV)
elif os.path.exists(ENV_PROD_EXAMPLE):
    load_dotenv(ENV_PROD_EXAMPLE)
elif os.path.exists(ENV_DEV_EXAMPLE):
    load_dotenv(ENV_DEV_EXAMPLE)

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get("BACKEND_SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('BACKEND_DEBUG', default=False, cast=bool)    

ALLOWED_HOSTS = [
    v.strip() for v in 
    os.environ.get("BACKEND_ALLOWED_HOSTS", "").split(",") 
    if v.strip()
]
# Settings for working behind (nginx)
USE_X_FORWARDED_HOST = True
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# Settings CSRF and sessions
CSRF_TRUSTED_ORIGINS = [
    v.strip() for v in 
    os.environ.get("BACKEND_CSRF_TRUSTED_ORIGINS", "").split(",") 
    if v.strip()
]

CSRF_COOKIE_SECURE = True
SESSION_COOKIE_SECURE = True
CSRF_COOKIE_SAMESITE = 'Lax'
SESSION_COOKIE_SAMESITE = 'Lax'

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # custom apps
    "app_api",
    "app_pages",
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # custom middleware
    'app_pages.middleware.StreamlitAccessMiddleware',
]

ROOT_URLCONF = 'app.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'app.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    # 'default': {
    #     'ENGINE': 'django.db.backends.sqlite3',
    #     'NAME': BASE_DIR / 'db.sqlite3',
    # },
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': config('DB_NAME'),
        'USER': config('BACKEND_DJANGO_DB_USER'),
        'PASSWORD': config('BACKEND_DJANGO_DB_PASSWORD'),
        'HOST': config('DB_HOST'),
        'PORT': config('DB_PORT'),
        'OPTIONS': {
            'options': f"-c search_path={config('BACKEND_DJANGO_DB_SCHEMA')}",
            'connect_timeout': 10, 
            'sslmode': 'require', 
            'client_encoding': 'UTF8',   
        },
        'CONN_MAX_AGE': 300,
        'ATOMIC_REQUESTS': True,
    }
}
 
# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'ru-ru'
TIME_ZONE = 'Europe/Moscow'
USE_I18N = True
USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [
    BASE_DIR / 'static', 
    BASE_DIR / 'app_api/static', 
    BASE_DIR / 'app_pages/static', 
]

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'


# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# Settings for production
if not DEBUG:
    SECURE_SSL_REDIRECT = True
    SECURE_HSTS_SECONDS = 31536000
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    SECURE_BROWSER_XSS_FILTER = True


# Settings for Fronted (Streamlit) proxy
STREAMLIT_INTERNAL_URL = config('FRONTEND_STREAMLIT_INTERNAL_URL')
STREAMLIT_PUBLIC_URL = '/streamlit/'


# Logging
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
        },
        'file': {
            'class': 'logging.FileHandler',
            'filename': BASE_DIR.parent / "settings"  / 'logs' / 'backend' / 'django.log',
            'formatter': 'verbose',
        },
    },
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {message}',
            'style': '{',
        },
    },
    'root': {
        'handlers': ['console', 'file'],
        'level': 'INFO',
    },
}